### PR TITLE
Add support for fetching intraday floors to get_intraday_data_limit_1d

### PR DESCRIPTION
**Pull request by Niggggggo**
Adds support for fetching intraday Floors used, can be used in Grafana like this:
image

### CODE REVIEW

**Comment by arpanghosh8453** [comment]
I think Fitbit deprecated floor counts in all of their recent releases ( I have a Charge 5, which lacks this feature altogether, but by Charge 4 had it ). Which device you are using? It may terminate the script if the endpoint is not available for the device.

**Comment by Niggggggo** [comment]
Hmm, it works for me on a Pixel Watch 2 just fine. Could you let me know what kind of errors it produces on your end so we can add handling for that?

**Comment by Niggggggo** [comment]
@arpanghosh8453 were you able to take a Look at this?

**Comment by arpanghosh8453** [comment]
@Niggggggo I had a look. On their official [Web API documentation](https://dev.fitbit.com/build/reference/web-api/) and the [Web API Explorer](https://dev.fitbit.com/build/reference/web-api/explore/), they have removed that endpoint, so I am assuming that is an leftover/soon-to-be-deprecated feature/API-endpoint. Including that might encounter issues with future releases. 

Additionally, if there was an documented endpoint for total floors count per day (similar to Calories or Distance walked per day) I would be interested to include that with proper error handling, but it seems the intraday data consumes too many requests being intraday, whereas providing not-so-interesting statistics (as it will always be 0-1 over time)

**Pull request closed without merging**
